# Generated by Django 5.2.17 on 2026-09-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('customer', 'Customer')], max_length=20)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RankingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('stale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AccountAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('kept_open', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('note', 'Note')], max_length=20)),
                ('occurred_at', models.DateField()),
                ('notes', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contact')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.customer')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
